### PR TITLE
trackme: New App - Version 1.0.0

### PR DESCRIPTION
**Pull request by guilhemmarchand**
#Release Notes

TrackMe Release Notes - Published by TrackMe Limited, April 13, 2024

Version 1.0.0 - Released April 13, 2024

- First release

### CODE REVIEW

**Comment by ishans-crest** [comment]
Hi @guilhemmarchand 

We have changed the action names for all the actions as they were not following the standards ("Action names should have lower-case and spaces"). They were using 'underscores' instead of 'spaces'. 

For example - the action name - "ack_get" has been changed to "get ack status"

Could you please verify if the new action names are correct or not? 
Please change the names if required, making sure of the standards. 

Thank You.

**Comment by guilhemmarchand** [comment]
Thank you very much @ishans-crest I have seen lots of actions indeed ;-)
Please allow me a few days to review this and I revert here!
Much appreciated

**Comment by ishans-crest** [comment]
Hi @guilhemmarchand 
Just a gentle follow-up. Do we have any update on the action name changes?

**Comment by guilhemmarchand** [comment]
Hi @ishans-crest !

thanks fo rthe reminder and sorry for the delay - on top of my todo list, I shall achieve final verifications tomorrow.

Many thanls!

**Comment by guilhemmarchand** [comment]
Hello @ishans-crest 

I am happy to confirm all changes passed my qualitification tests, and happy to confirm the release is ready from my perspective - thank you for your help on these.

Guilhem

**Comment by guilhemmarchand** [comment]
Hi @ishans-crest 
Feel free to let me know if you need anything further from me or if we are good to go now ;-)
Thanks

**Comment by ishans-crest** [comment]
@guilhemmarchand 
Thank you for the submission. We are good to go now. 
Just an FYI. We have also changed the action result output column names based on our standards. eg - 'maintenance_message' to 'Maintenance Message'

**Comment by guilhemmarchand** [comment]
@ishans-crest 

> Just an FYI. We have also changed the action result output column names based on our standards. eg - 'maintenance_message' to 'Maintenance Message'

understood - happy with that

**Comment by guilhemmarchand** [comment]
Hi @ishans-crest !

Hope you're good - May I ask what is the next step so the PR gets merged and the first version published?

**Comment by ishans-crest** [comment]
Hi @guilhemmarchand 
We are done with the changes from our end. 
Based on our standards, we had to update the application code( without modifying any functionalities). Could you please test the latest code from your end?

Thanks.

**Comment by guilhemmarchand** [comment]
Hi @ishans-crest 

I am happy to confirm that my qualification tests are successful, and no regression were detected compared to the original code.

Guilhem

**Review by mishalp-crest — APPROVED** [review]

**Review by mmomin-crest — APPROVED** [review]

**Review by ishans-crest — APPROVED** [review]

**Pull request merged**
